---
title: "ACM School Placement"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Read Data

This data is mockup data generated by staff for demo.

```{r}
install.packages("readxl")
library(readxl)
student_df <- read_excel(path = "C:\\Users\\CLuedtke.CITYYEAR\\Downloads\\Input 1 - ACM Data.xls")
school_df <- read_excel(path = "C:\\Users\\CLuedtke.CITYYEAR\\Downloads\\Input 2 - School Data.xls")

school_df$id <- 1:nrow(school_df)

```

# Build Requirements

```{r generate logic for invalid assignments}
# E.g., can't allow staff with age < 21 into an HS

IsValid <- function(assign){
  valid <- ifelse(any(assign < 9), FALSE, TRUE) 
  return(valid)
}
```


```{r randomly generate initial assignment}

random.gen <- function(student_df, school_df){
  nSch <- nrow(school_df)
  nStu <- nrow(student_df)
  team.size <- ceiling(nStu/nSch)
  assign <- rep(school_df$id, each = team.size) # Creates a vector of 1 10 times, 2 10 times, etc
  random <- sample(x = assign, size = nStu)
    # table(random) # ... This displays a tabulation of the assigned schools
  return(random)
}

repeat{
  myAssign <- random.gen(student_df, school_df)
  table(myAssign)
  if (IsValid(myAssign)) break
}
```

```{r generate proposal function for algorithm's steps}
GenProp <- function(myAssign){
  # picks random to and from schools, and swaps those assignments
  # returns the full assignment
}
```


```{r create objective function}
Obj <- function(myAssign){
  # Takes the assignment, and calculations an objective score combining:
  # 1. minimize commute time
  # 2. college experience or age >= 21 for HS (might also be requirement for valid proposal)
  # 3. bonus for demographic balance (e.g. gender, race/eth, ed)
  # 4. grade-level and perhaps even school preferences
  
  
}
```

```{r create a temperature schedule as a function of step number}

```

```{r implement SA algorithm}

```


# To DO

* hard and soft criteria
* picking initial 'direction'
  * how to set up function to know that there are teams of 9
  * output: series ()
* Identify right solution algorithm for our setup
  * GenSA
  * gaoptim -- is for permutation-based problems
  * roll our own (Nick has code for this)

