---
title: "Simulated Annealing Demo"
author: "Alex Perusse"
date: "May 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We'll create a quick demo of Simulated Annealing for a simplified traveling salesman problem. 

```{r Problem Statement}
# Generate 50 cities to work with
randomCities <- function() { 
  id <- 1:50
  x <- sample(1:100, 50, replace=T)
  y <- sample(1:100, 50, replace=T)
  data.frame(cbind(id, x, y))
}

# Calculate distance between two given cities.
# Assume we're given the indices of two cities.  Distance is calculated from there.
distanceTo <- function(from, to) {   
  from_coords <- cities[from, ]
  to_coords <- cities[to, ]
  
  x_diff <- (from_coords$x - to_coords$x)^2
  y_diff <- (from_coords$y - to_coords$y)^2
  
  sqrt(x_diff + y_diff)
}

# For each starting point, assign a city number w/o replacement.  
initialAssignment <- function() {
  start <- 1:50
  end <- sample(1:50, 50, replace=F)
  
  data.frame(cbind(start, end))
}

scoreAssignment <- function(assignment) {
  assignment$distances <- distanceTo(assignment$start, assignment$end)
  sum(assignment$distances)
}

swap <- function(assignment, first, second) {
  fst <- assignment[first, ]$end
  assignment[first, ]$end <- assignment[second, ]$end
  assignment[second, ]$end <- fst
  assignment
}

acceptanceProbability <- function(currentScore, newScore, temp) {
  ifelse(newScore < currentScore, 1, exp((currentScore - newScore) / temp))
}

coolTemp <- function(temp, coolingRate) {
  temp*(1-coolingRate)
} 

simpleSA <- function(locs, temp=1000, coolingRate=0.003, global_iters=10000) {
  
  n_cities <- nrow(locs)
  
  currentAssign <- initialAssignment()
  currentScore <- scoreAssignment(currentAssign)
  
  while(temp > 1 | global_iters > 0) {
    swp <- sample(n_cities, 2)
    
    testAssign <- swap(currentAssign, swp[1], swp[2])
    testScore <- scoreAssignment(testAssign)
    
    if (acceptanceProbability(currentScore, testScore, temp) > runif(1)) {
      currentAssign <- testAssign
      currentScore <- testScore
    }
    
    temp <- coolTemp(temp, coolingRate)
    global_iters <- global_iters - 1
  }
  
  currentAssign
}
```

```{r}
simpleSA(cities)
```

```{r Extending to the TSP}
cities <- randomCities()

addCity <- function(tour, city) {
  tourSize <- nrow(tour)
  tour[tourSize+1, 1] <- tour[tourSize, 2]
  tour[tourSize+1, 2] <- city
  tour
}

initialTour <- function(cities) {
  rCities <- data.frame(sample(2:50, 49, replace=F))
  tour <- data.frame(from=1, to=rCities[1, ])
  
  for (city in rCities[2:nrow(rCities), ]){
    tour <- addCity(tour, city)
  }
  
  tour <- addCity(tour, 1)
  
  tour
}

reverseTour <- function(tour, start, end) {
  tour[start:end, 2] <- tour[end:start, 2]
  tour
}

distanceTo <- function(from, to) {   
  from_coords <- cities[cities$id == from, ]
  to_coords <- cities[cities$id == to, ]
  
  x_diff <- (from_coords$x - to_coords$x)^2
  y_diff <- (from_coords$y - to_coords$y)^2
  
  sqrt(x_diff + y_diff)
}

scoreTour <- function(tour) {
  sum(mapply(distanceTo, tour$from, tour$to))
}

travelingSA <- function(locs, temp=1000, coolingRate=0.003, global_iters=10000) {
  
  n_cities <- nrow(locs)
  
  currentAssign <- initialTour(cities)
  currentScore <- scoreTour(currentAssign)
  
  while(global_iters > 0) {
    swp <- sample(n_cities, 2)
    
    testAssign <- reverseTour(currentAssign, swp[1], swp[2])
    testScore <- scoreTour(testAssign)
    errors <- data.frame(iter=c(1), score=c(currentScore))
    
    if (acceptanceProbability(currentScore, testScore, temp) > runif(1)) {
      currentAssign <- testAssign
      currentScore <- testScore
    }
    
    errors <- rbind(errors, data.frame(iter=c(global_iters), score=c(currentScore)))
    temp <- coolTemp(temp, coolingRate)
    global_iters <- global_iters - 1
  }
  
  currentAssign
}

tour <- initialTour(cities)

travelingSA(cities)
```

