```{r Inputs}
rm(list=ls(all=TRUE))

dataset <- data.frame(FP = 1)
dataset$FP[1] <-"C:\\Users\\CLuedtke\\ACM-School-Placement\\"
dataset$prevent_roommates[1] <-"NO"
dataset$number_iterations[1] <- 500
dataset$consider_commutes[1] <- "No"
dataset$used_surveygizmo[1] <- "No"
dataset$create_ij[1] <- "Yes"

dataset$commute_factor = 1
dataset$age_factor = 1
dataset$ethnicity_factor= 1
dataset$Edscore_factor = 1
dataset$Tutoring_factor = 1
dataset$Spanish_factor = 1
dataset$Math_factor = 1
dataset$Gender_factor = 1

# TO DO
# - scores that can be manually balanced
# - squash ALL the bugs
# - play with temperature schedule?
# - IJ placements
# - survey senior IMs for a balance of scores on 100 point scale
# - Calculate % score improved from random placement, and display that to user to inform weight setting
# - Make fake team placements -> Make IJ from fake team placements
# - Make IJ placements but encourage bad commutes
# - When making team placements, prevent IJ conflicts
# - also prevent TL from having teammates




# - add team leader column


# TWO OPTIONS
# - Place school teams AFTER IJ teams
#   - make fake school teams first, then make fake IJ teams that prevent school teammates from being on the same IJ.
#   - make IJ teams with the same process as school teams, but seek to maximize commutes to the TL's school. That way, hopefully no ACM is prevented from serving at a close school due to IJ conflicts.

#   - construct lists of IJ teams with TL
#   - create function that determintes eligible placements

# - If placing IJ teams after school teams
#   - 

# Firm things
#   - Roommates
#   - IJ/school team
#   - HS eligible
#   - Manual Placements


# Use cases
# - either create IJ teams and prevent school teammates from being on same IJ team
# - OR create school teams and prevent IJ teammates from being on the same school team

# Manual Balance of Scores Brainstorming

# Commutes
#   Average commute time of __ minutes
# Age Diversity
#   Average team age diversity (variance) is __ percent different from corps-wide age diversity
# Ethnic Diversity
#   Average ACM experiences that __ percent of their team shares their ethnicity
# scores$Edscore <- hs_loss(placed$HSGrad_tgt, placed$HS_Grads) + sum((placed$SomeCol_tgt - placed$SomeCol)^2)
# Tutoring Experience Diversity
#   Average team tutoring experience diversity is __ percent of corps-wide age diversity
# scores$Tutoring <- sum((placed$TutExp - placed$Tutoring)^2)
# Spanish Slots Filled
#   __ percent of Spanish speaker slots filled
# scores$Spanish <- (reqd_spanish_loss(placed$SpanishNeed, placed$Spanish, min_reqd = 1) + sum((placed$OtherLang_tgt - placed$OtherLang)^2))
# Math Ability Diversity
# scores$Math <- sum((placed$Math_tgt - placed$MathAble)^2)
# Gender Diversity
# scores$Gender <- reqd_males(placed$Male_tgt, placed$Males, 1)

```

```{r}
# 'dataset' holds the input data for this script
library(readxl)
library(dplyr)
library(tidyr)
library(data.table)

root_dir <- dataset$FP[1]
prevent_roommates <- dataset$prevent_roommates[1]
number_iterations <- dataset$number_iterations[1]
consider_commutes <- dataset$consider_commutes[1]
used_surveygizmo <- dataset$used_surveygizmo[1]

# Adjusted Factors
#sum_factors <- sum(c(dataset$commute_factor, dataset$age_factor, dataset$ethnicity_factor, #dataset$Edscore_factor,dataset$Tutoring_factor,dataset$Spanish_factor,dataset$Math_factor,dataset$Gender_factor))
#
#dataset$commute_factor = dataset$commute_factor/sum_factors
#dataset$age_factor = dataset$age_factor/sum_factors
#dataset$ethnicity_factor = dataset$ethnicity_factor/sum_factors
#dataset$Edscore_factor = dataset$Edscore_factor/sum_factors
#dataset$Tutoring_factor = dataset$Tutoring_factor/sum_factors
#dataset$Spanish_factor = dataset$Spanish_factor/sum_factors
#dataset$Math_factor = dataset$Math_factor/sum_factors
#dataset$Gender_factor = dataset$Gender_factor/sum_factors

acm_df <- read.csv(file = paste(root_dir, "Input 1 - ACM Data.csv", sep = ""), check.names=FALSE, stringsAsFactors = FALSE)

if(consider_commutes == "Yes"){
  acm_commutes <- read.csv(file = paste(root_dir, "ACM Commutes.csv", sep = ""), check.names=FALSE)
  acm_commutes$Commute.Time <- as.numeric(as.character(acm_commutes$Commute.Time))
  acm_commutes$id_dest <- paste(acm_commutes$acm_id, acm_commutes$School, sep = "_")
  dt_commutes <- data.table(acm_commutes)
}

school_df <- read_excel(path = paste(root_dir, "Input 2 - School Data.xls", sep = ""))

rename_headers <- function(acm_df){
  vars_df <- read_excel(path = paste(root_dir, "Survey Items to Variable Names.xls", sep = ""))
  
  # Rename Headers
  for (x in names(acm_df)){
    if(x %in% vars_df$Survey.Item){
      names(acm_df)[names(acm_df) == x] <- as.character(vars_df$Variable.Name[vars_df$Survey.Item == x])
    }
  }
  
  acm_df
}

if(used_surveygizmo == "Yes"){
  acm_df <- rename_headers(acm_df)
}

# Create One Race.Ethnicity Column
ethn_cols = c("Race.Ethnicity.African.American.Black",
              "Race.Ethnicity.American.Indian.Alaskan.Native",
              "Race.Ethnicity.Asian",
              "Race.Ethnicity.Hispanic.Latino",
              "Race.Ethnicity.Middle.Eastern",
              "Race.Ethnicity.Native.Hawaiian.Pacific.Islander",
              "Race.Ethnicity.White.Caucasian", 
              "Race.Ethnicity.Other")

acm_df[, ethn_cols][acm_df[, ethn_cols] == ""] <- NA

acm_df$Race.Ethnicity <- apply(acm_df[, ethn_cols], 1, function(x) toString(na.omit(x)))

clean_roommates <- function(acm_df){
  cols <- c("Roommate.Names1",
            "Roommate.Names2",
            "Roommate.Names3",
            "Roommate.Names4",
            "Roommate.Names5")
  
  roommates_df <- acm_df[acm_df$Roommates == 'Yes'
                         | acm_df$Full.Name %in% unlist(acm_df[, cols], use.names = FALSE), ]
  
  acm_df$Roommate.Names <- NA
  
  for (x in roommates_df$Full.Name){
    # Select any rows containing ACM name
    other_roommates <- subset(roommates_df, apply(roommates_df, 1, function(y){any(y == x)}))
    
    cols <- c("Full.Name", cols)
    
    # Select unique roommate names
    roommates_list <- unique(unlist(other_roommates[, cols], use.names = FALSE))
    roommates_list <- roommates_list[!is.na(roommates_list) & (roommates_list != "")]
    roommates_list <- sort(roommates_list)
    
    acm_df$Roommate.Names1[acm_df$Full.Name == x] <- roommates_list[1]
    acm_df$Roommate.Names2[acm_df$Full.Name == x] <- roommates_list[2]
    acm_df$Roommate.Names3[acm_df$Full.Name == x] <- roommates_list[3]
    acm_df$Roommate.Names4[acm_df$Full.Name == x] <- roommates_list[4]
    acm_df$Roommate.Names5[acm_df$Full.Name == x] <- roommates_list[5]
    
    acm_df$Roommate.Names[acm_df$Full.Name == x] = paste(roommates_list, collapse=", ")
  }
  acm_df
}

acm_df <- clean_roommates(acm_df)

school_df$sch_id <- 1:nrow(school_df)

#  Encode Variables & Clean Up Input Dataframes

#Before being able to calculate a score, we'll need to encode all of our variables numerically.  For categorical ## variables, we can create a dummy variable for all except one of the categories (this is because the last category can be inferred).

# This function takes the input acm_df and encodes the variables in a way that makes the mathematically tractable.

encode_acm_df <- function(df){

  acm_enc <- select(acm_df, acm_id, Math.Confidence)
  
  # Ed Attainment
  acm_enc$Ed_HS <- as.numeric(grepl("High School/GED", df$Educational.Attainment))
  acm_enc$Ed_SomeCol <- grepl("Some College", df$Educational.Attainment) + grepl("Associate's Degree", df$Educational.Attainment)
  acm_enc$Ed_Col <- grepl("Bachelor's Degree", df$Educational.Attainment) + grepl("Master's Degree", df$Educational.Attainment)
  
  # Tutoring Experience
  acm_enc$HasTutored <- as.numeric(grepl("Yes", df$Tutoring.Experience))

  # Language Ability
  acm_enc$SpanishAble <- as.numeric(grepl("Spanish", df$Language.Ability.Spanish))
  acm_enc$Lang_Other <- ifelse(grepl("Spanish", df$Language.Ability.Spanish) == F & grepl("Yes", df$Language.Other.English), 1, 0)
  
  # Gender
  acm_enc$Male <- as.numeric(grepl("Male", df$Gender))
  acm_enc$Other.Gender <- as.numeric(grepl("Other", df$Gender))
  
  # Math Confidence
  acm_enc$Math.Confidence <- as.numeric(grepl(paste(c("Algebra I", "Algebra II", "Trigonometry", "Calculus or higher"), collapse = "|"), acm_enc$Math.Confidence))

  # Add in other features
  acm_enc <- acm_enc %>%
               left_join(., select(df,
                                   acm_id,
                                   Gender, 
                                   Manual.Placement, 
                                   Birth.Date,
                                   Race.Ethnicity,
                                   Roommate.Names),
                                  
                         by=c("acm_id" = "acm_id")) %>%
               mutate(days_old = as.integer(Sys.Date() - as.Date(as.character(df$Birth.Date), format="%m/%d/%Y"))) %>%
               replace_na(list(Lang_Other = 0, days_old = 0))

  # Return
  acm_enc
}

# This function calculates some import counts which I'm going to use a lot when trying to figure out the expected number of ACMs per team per metric.  This function will just be used internally by the school_config function.
corps_demographic_targets <- function(school_df, acm_enc){
  # Calculate some totals used later in the function
  N <- nrow(acm_enc)
  S <- nrow(school_df)
  
  # Counts of schools by level
  school_counts <- group_by(school_df, GradeLevel) %>% summarise(count=n())
  
  # Approximation of densly spanish speaking schools
  dense_hispanic <- nrow(school_df[school_df$`% Hispanic` > 10, ])
  
  # We'll store our results in a list so we can return multiple tables
  distros <- list()
  
  # Produce ratio of folks who have completed at least an associates, and those who haven't
  distros$education <- data.frame(level = c("HS", "SomeCol"), ratio = c(nrow(acm_enc[acm_enc$Ed_HS == 1,]) / N, nrow(acm_enc[acm_enc$Ed_SomeCol == 1,]) / N))
  
  # Identify rates of Tutoring Experience
  distros$tut_exp <- group_by(acm_enc, HasTutored) %>% 
    summarise(count=n()) %>% 
    mutate(ratio = count/N)
  
  # Spanish and other spoken language distribution
  distros$lang <- data.frame(ability = c("spanish","other"), ratio = c(nrow(acm_enc[acm_enc$SpanishAble == 1, ]) / N, nrow(acm_enc[acm_enc$Lang_Other == 1, ]) / N))
  
  # Math Ability
  distros$math <- nrow(acm_enc[acm_enc$Math.Confidence == 1,]) / N
  
  # Gender
  distros$gender <- nrow(acm_enc[(acm_enc$Male == 1) | (acm_enc$Other.Gender == 1), ]) / N
  
  distros
}

# I derived this function mildly arbitrarily. The logic is that we probably want at least one spanish speaker at a school, but there are then diminishing returns.  It scales so that for a school that 100% hispanic, we would aim to have 2.6 spanish speakers on the team.  A team thats 80% hispanic will aim to have 4. The main problem with this approach is that we may create too many spots for spanish speakers, or have not have enough spanish speakers for the intended spots.  
# Shifted down by 75% for LA, since everyone has over 80% Hispanic

spanishNeed <- function(x) {
  1.5772*log(x) - 2.1205
}

# Directly calculates the expected number of ACMs per team for each of the markers.
# My methodology is to aim for a uniform distribution when it makes sense.

school_config <- function(school_df, acm_enc){
  # Precalculate some helpful counts
  corps_demos <- corps_demographic_targets(school_df, acm_enc)
  # Unravel list into some variables.  Mostly so that the code is a little cleaner later.
  education <- corps_demos$education
  lang <- corps_demos$lang
  tut_exp <- corps_demos$tut_exp
  math <- corps_demos$math
  gender <- corps_demos$gender
  
  
  school.data <- select(school_df, `sch_id`, `School`, `Team Size`, `GradeLevel`, `% Hispanic`) %>%
    rename(size = `Team Size`,
           span = `GradeLevel`) %>%
    mutate(HSGrad_tgt = ifelse(span=="High", 0, education[education$level %in% 'HS',]$ratio * as.numeric(size)),
           SomeCol_tgt = education[education$level %in% 'SomeCol',]$ratio * as.numeric(size),
           TutExp = as.numeric(size) * tut_exp[tut_exp$HasTutored == 1,]$ratio,
           SpanishNeed = pmax(spanishNeed(`% Hispanic`), 1),# This sets a minimum of 1 spanish speaker per team.  This might make sense in LA, but not other places.
           OtherLang_tgt = lang[lang$ability %in% 'other',]$ratio * as.numeric(size),
           Math_tgt = ifelse(span=="Elementary", as.numeric(size)*.5*math, ifelse(span=="Middle", .75*as.numeric(size)*math, as.numeric(size)*math)),
           Male_tgt = as.numeric(size)*gender)
}


prev_roommates <- function(school_targets, team_placements_df){
  
  roommie_violations <- 
    team_placements_df %>% 
      filter(!is.na(Roommate.Names)) %>%
      group_by(placement) %>%
      count(Roommate.Names) %>%
      filter(n > 1)
  
  school_ids <- 1:nrow(school_targets)
  schools_to_swap <- c(0, 0)
  
  for (z in  roommie_violations$Roommate.Names){
    
    schools_to_swap[1] <- roommie_violations$placement[roommie_violations$Roommate.Names == z]
        
    roommate_set <- team_placements_df[which(team_placements_df$Roommate.Names == z), ]
    
    roommate_set_no_manual <- roommate_set[is.na(roommate_set$Manual.Placement), ]
    
    acm_to_keep <- 0
    
    # if no roommates were manually placed, choose one to keep
    if (all(is.na(roommate_set$Manual.Placement))){
      acm_to_keep <- sample(roommate_set_no_manual$acm_id, 1)
    }
    
    # swap out all ACMs who were not manually placed or chosen to be acm_to_keep
    for (k in roommate_set_no_manual$acm_id[!(roommate_set_no_manual$acm_id %in% acm_to_keep)]){
      swap1 <- k
      swap1_roommates <- z
      
      # flag schools with roommate conflicts
      ineligible_schools <- 
        team_placements_df %>%
          filter(!is.na(Roommate.Names)) %>%
          group_by(placement) %>%
          summarise(n = sum(Roommate.Names %in% swap1_roommates)) %>%
          filter(n > 0)

      schools_to_swap[2] <- sample(school_ids[!(school_ids %in% ineligible_schools$placement)], 1)
      
      # find acm in schools_to_swap[2] who does not have roommates on schools_to_swap[1] (and who was not manually placed)
      school1_roommates <- team_placements_df$Roommate.Names[team_placements_df$placement == schools_to_swap[1]]
      # filter for ACMs on schools_to_swap[2] with no Manual.Placement
      school2_frame <- team_placements_df[(team_placements_df$placement == schools_to_swap[2] & is.na(team_placements_df$Manual.Placement)), ]
      
      # choose a swap2 on schools_to_swap[2] whose roommates are not on schools_to_swap[1]
      swap2 <- sample(school2_frame$acm_id[(is.na(school2_frame$Roommate.Names))
                                           | !(school2_frame$Roommate.Names %in% school1_roommates)], 1)
      
      # Swap the team placement of those 2 ACMs
      team_placements_df$placement <- replace(team_placements_df$placement, c(swap1, swap2), team_placements_df$placement[c(swap2, swap1)])
    }
  }

  # swap out ACMs with only HS education who were assigned to HS
  acms_for_swaps <- merge(team_placements_df[is.na(team_placements_df$Manual.Placement), ], school_targets, by.x = "placement", by.y = "sch_id", all.x = TRUE)
  
  hs_acm_to_swap <- acms_for_swaps[(acms_for_swaps$Ed_HS == 1) & (acms_for_swaps$span == "High"), ]
  
  for (x in hs_acm_to_swap$acm_id){
    acms_for_swaps <- merge(team_placements_df[is.na(team_placements_df$Manual.Placement), ], school_targets, by.x = "placement", by.y = "sch_id", all.x = TRUE)
    
    swap1 <- x
    
    schools_to_swap[1] <- team_placements_df$placement[team_placements_df$acm_id == swap1]

    swap1_roommates <- team_placements_df$Roommate.Names[team_placements_df$acm_id == swap1]
    
    # flag schools with roommate conflicts with swap1_roommates
    ineligible_schools <- 
      team_placements_df %>%
        filter(!is.na(Roommate.Names)) %>%
        group_by(placement) %>%
        summarise(n = sum(Roommate.Names %in% swap1_roommates)) %>%
        filter(n > 0)
    
    # Sample from non-HS schools without roommate conflicts
    schools_to_swap[2] <- sample(school_ids[!(school_ids %in% ineligible_schools$placement) 
                                            & !(school_ids %in% schools_to_swap[1])
                                            & (school_ids %in% acms_for_swaps$placement[acms_for_swaps$span != "High"])], 1)
    
    # find acm in schools_to_swap[2] who does not have roommates on schools_to_swap[1], was not manually placed, and is HS-eligible
    school1_roommates <- team_placements_df$Roommate.Names[team_placements_df$placement == schools_to_swap[1]]
    school2_frame <- acms_for_swaps[(acms_for_swaps$placement == schools_to_swap[2] & acms_for_swaps$Ed_HS == 0), ]
    
    # choose a swap2 in school2_frame whose roommates are not on schools_to_swap[1]
    swap2 <- sample(school2_frame$acm_id[(is.na(school2_frame$Roommate.Names)
                                          | !(school2_frame$Roommate.Names %in% school1_roommates))], 1)
    
    # Swap the team placement of those 2 ACMs
    team_placements_df$placement <- replace(team_placements_df$placement, c(swap1, swap2), team_placements_df$placement[c(swap2, swap1)])
      
  }
  
  return(team_placements_df)
}


initial_placement <- function(acm_enc, school_targets, prevent_roommates){
  # First place acm's at schools designated by Manual.Placement column
  # NOTE: Removed seed parameter.  Seed is used for reproducability, but we want randomness in the start.
  
  # first create an empty list
  team_placements = list()
  
  acm_enc$Manual.Placement <- as.character(acm_enc$Manual.Placement)
  is.na(acm_enc$Manual.Placement) <- acm_enc$Manual.Placement == ''
  
  acms_with_Manual.Placement <- acm_enc %>%
                                  left_join(., select(school_targets, sch_id:School), 
                                            by=c("Manual.Placement" = "School")) %>%
                                  filter(!is.na(sch_id))
  
  filled_slot_counts <- acms_with_Manual.Placement %>%
                          group_by(sch_id) %>%
                          summarise(filled = n())
  
  team_size_targets <- select(school_targets, sch_id:size) %>%
                        left_join(., filled_slot_counts, by=("sch_id")) %>%
                        replace_na(list(filled = 0)) %>%
                        mutate(unfilled_slots = as.numeric(size) - as.numeric(filled))
  
  # use a for-loop to assign each survey respondent (who was not already manually placed) to a team
  for (x in team_size_targets$sch_id){
    team_slots = list(
      # create a list that repeats each school 'id' for the size of each team
      rep(x, 
          subset(team_size_targets$unfilled_slots, team_size_targets$sch_id == x)
          )
      )
    team_placements <- c(team_placements, team_slots)
  }
  
  # non-random placements of CMs who were not manually placed  
  team_placements <- data.frame(placement=unlist(team_placements))
  
  # Number of survey respondents who were just placed
  slots <- nrow(team_placements)

  # List of ACM ids of survey respondents who were not manually placed, plus dummy id's for team slots that were not filled by any survey respondent
  if (nrow(acm_enc) == sum(team_size_targets$size)){
    filled_acm_roster <- acm_enc[is.na(acm_enc$Manual.Placement), ]$acm_id
  } else {
    filled_acm_roster <- c(acm_enc[is.na(acm_enc$Manual.Placement), ]$acm_id, 
                         (nrow(acm_enc)+1):sum(team_size_targets$size))
  }
  
  # Randomize Starting Place

  team_placements_df <- data.frame(sch_id=team_placements[sample(nrow(team_placements), replace=F), ],
                                   acm_id= filled_acm_roster) %>%
                        union(., select(acms_with_Manual.Placement, sch_id, acm_id)) %>%
                        rename(placement = sch_id)
  

  # Merge team_placements_df with acm_df on the 'id' column
  team_placements_df <- left_join(team_placements_df, acm_enc, by = "acm_id") %>%
                        replace_na(replace = list(Math.Confidence = 0, 
                                                  Ed_HS = 0, 
                                                  Ed_SomeCol = 0, 
                                                  Ed_Col = 0,
                                                  HasTutored = 0, 
                                                  SpanishAble = 0, 
                                                  Lang_Other = 0, 
                                                  Male = 0, 
                                                  Other.Gender =0, 
                                                  days_old = 0))

  # Sort by acm_id and reset the index
  team_placements_df <- team_placements_df[order(team_placements_df$acm_id), ]
  rownames(team_placements_df) <- 1:nrow(team_placements_df)
  
  # Prevent Roommates from being on the same team
  if (prevent_roommates == "Yes"){
    team_placements_df <- prev_roommates(school_targets, team_placements_df)
  
  } else {

  # We would like to ensure that high school students get placed in ES or MS. Select ACMs who were not manually placed.
  acms_for_swaps <- merge(team_placements_df[is.na(team_placements_df$Manual.Placement), ], school_targets, by.x = "placement", by.y = "sch_id", all.x = TRUE)
  
  # Select ACMs with only HS education and who were assigned to a high school  
  hs_acms_to_swap <- acms_for_swaps[(acms_for_swaps$Ed_HS == 1) & (acms_for_swaps$span == "High"),]
  # Select ACMs with higher than HS education and who were not assigned to a high school  
  acms_to_swap_with <- acms_for_swaps[(acms_for_swaps$Ed_HS == 0) & (acms_for_swaps$span != "High"),]
  
  acms_to_swap_with <- acms_to_swap_with[sample(nrow(acms_to_swap_with), nrow(hs_acms_to_swap), replace=F), ]
  
  team_placements_df[team_placements_df$acm_id %in% hs_acms_to_swap$acm_id, ]$placement <- acms_to_swap_with$placement
  team_placements_df[team_placements_df$acm_id %in% acms_to_swap_with$acm_id, ]$placement <- hs_acms_to_swap$placement
  
  }

  return(team_placements_df)
  
}

# Calculate score

hs_loss <- function(targets, actuals){
  loss <- ifelse(targets == 0, (targets - actuals) * -1e10, (targets - actuals)^2)
  sum(loss)
}

reqd_spanish_loss <- function(targets, actuals, min_reqd = 1){
  loss <- ifelse(actuals < min_reqd, 1e10, (targets - actuals)^2)
  sum(loss)
}

reqd_males <- function(targets, actuals, min_reqd = 1){
  loss <- ifelse(actuals < min_reqd, 1e10, (targets - actuals)^2)
  sum(loss)
}

calculate_score = function(team_placements_df, school_targets, gender_target=gender_g) {
  
  # Merge  with school_df to pull in school characteristics
  team_placements_df <- merge(team_placements_df, school_targets, by.x = "placement", by.y = "sch_id", all.x = TRUE)
  
  # Store each score in a list
  scores = list()
  
  #################
  # COMMUTE SCORE #
  #################
  
  # This score is simply the sum number of seconds each ACM travels to their assigned school
  if(consider_commutes == "Yes"){
    
    team_placements_df$id_dest <- paste(team_placements_df$acm_id, team_placements_df$School, sep = "_")
    
    # Take the sqrt to scale the value closer to the other features
    scores$commute_score <- dt_commutes[id_dest %in% team_placements_df$id_dest, sum((Commute.Time^1.2), na.rm = TRUE)] * dataset$commute_factor
    
  } else {
    scores$commute_score <- 0
  }
  
  #############
  # AGE SCORE #
  #############
  
  # This score is the difference between the [overall age variance across the corps] and [overall average of each team's average age variance]
 
  age_var <-
    group_by(team_placements_df, placement) %>%
    summarize(age_var = var(days_old)) %>%
    ungroup() %>%
    summarize(avg_age_var = mean(age_var))

  scores$age_score <- abs(age_var$avg_age_var - var(team_placements_df$days_old)) /10 * dataset$age_factor

  ###################
  # ETHNICITY SCORE #
  ###################
  
  # This score is the overall average of each team's average % representation that each teammate experiences. For example, 0.44 means that for the average team, the average teammate experiences that his/her personal ethnicity is represented in 44% of the team.
  ethnicity_eths <- 
    team_placements_df %>%
    filter(!is.na(Race.Ethnicity)) %>%
    group_by(placement, 
             Race.Ethnicity) %>%
    summarize(n_eths = n()) %>%
    group_by(placement) %>%
    mutate(pct_eths = n_eths/sum(n_eths) * n_eths / sum(n_eths)) %>%
    mutate(avg_eths_rep = sum(pct_eths)) %>%
    summarize(avg_eths_rep = mean(avg_eths_rep)) %>%
    summarize(avg_eths_rep = mean(avg_eths_rep))

  scores$ethnicity_score <- ethnicity_eths$avg_eths_rep * 1000 * dataset$ethnicity_factor

  #################
  #    Scoring    #
  #################  
  
  placed <- team_placements_df %>%
                group_by(placement) %>%
                summarise(HS_Grads = sum(Ed_HS),
                          SomeCol = sum(Ed_SomeCol),
                          Tutoring = sum(HasTutored),
                          Spanish = sum(SpanishAble),
                          OtherLang = sum(Lang_Other),
                          MathAble = sum(Math.Confidence),
                          Males = sum(Male)) %>%
                left_join(., school_targets, by=c("placement" = "sch_id"))
  
  scores$Edscore <- (hs_loss(placed$HSGrad_tgt, placed$HS_Grads) + sum((placed$SomeCol_tgt - placed$SomeCol)^2)) * dataset$Edscore_factor
  scores$Tutoring <- sum((placed$TutExp - placed$Tutoring)^2) * dataset$Tutoring_factor
  scores$Spanish <- (reqd_spanish_loss(placed$SpanishNeed, placed$Spanish, min_reqd = 1) + sum((placed$OtherLang_tgt - placed$OtherLang)^2)) * dataset$Spanish_factor
  scores$Math <- sum((placed$Math_tgt - placed$MathAble)^2) * dataset$Math_factor
  scores$Gender <- reqd_males(placed$Male_tgt, placed$Males, 1) * dataset$Gender_factor

  #################
  # OVERALL SCORE #
  #################
  
  scores$aggr_score <- sum(unlist(scores))
  
  return(scores)
}


# Temperature Function

current_temperature = function(iter, s_curve_amplitude, s_curve_center, s_curve_width) {
  s_curve_amplitude * s_curve(iter, s_curve_center, s_curve_width)
}

s_curve = function(x, center, width) {
  1 / (1 + exp((x - center) / width))
}

# Annealing and Swap Function

run_intermediate_annealing_process = function(starting_placements, school_df, best_placements=starting_placements, best_score=1e12, starting_iteration=1, number_of_iterations, center_scale, width_scale) {
  
  team_placements_df <- starting_placements
  
  # Sort by acm_id so that each row index will equal acm_id
  team_placements_df <- team_placements_df[order(team_placements_df$acm_id), ]
  rownames(team_placements_df) <- 1:nrow(team_placements_df)
  
  placement_score <- calculate_score(starting_placements, school_df)$aggr_score
  trace <- data.frame(iter=c(1:(number_of_iterations+2)), 
                      commute_score = 0,
                      age_score = 0,
                      ethnicity_score= 0,
                      Edscore = 0,
                      Tutoring= 0,
                      Spanish = 0,
                      Math = 0,
                      Gender = 0,
                      score=0)
  
  trace[1, 2:10] <- calculate_score(starting_placements, school_df)

  for(i in 1:number_of_iterations) {
    iter = starting_iteration + i
    temp = current_temperature(iter, 3000, number_of_iterations * center_scale, number_of_iterations * width_scale)
    
    # Create a copy of team_placements_df
    candidate_placements_df <- team_placements_df
    acms_no_Manual.Placement <- subset(candidate_placements_df, (is.na(candidate_placements_df$Manual.Placement)))

    # Choose 2 schools at random
    school_ids <- 1:nrow(school_df)
    schools_to_swap <- sample(school_ids, 2)

    # Choose 1 ACM from each of those schools. Select only ACMs who have no Manual.Placement.
    swap1 <- sample(acms_no_Manual.Placement$acm_id[ acms_no_Manual.Placement$placement == schools_to_swap[1] ], 1)
    swap2 <- sample(acms_no_Manual.Placement$acm_id[ acms_no_Manual.Placement$placement == schools_to_swap[2] ], 1)
    
    # if preventing roommates
    if (prevent_roommates == "Yes"){
      # find schools that do not contain swap1's roommates
      swap1_roommates <- candidate_placements_df$Roommate.Names[candidate_placements_df$acm_id == swap1]
      
      # find schools where no roommate conflict exists with swap1. Filter out NA's in Roommate.Names so that a swap1 with NA roommates will have no conflicts on any team.
      ineligible_schools <- 
        candidate_placements_df %>%
          filter(!is.na(Roommate.Names)) %>%
          group_by(placement) %>%
          summarise(n = sum(Roommate.Names %in% swap1_roommates)) %>%
          filter(n > 0)
      
      schools_to_swap[2] <- sample(school_ids[!(school_ids %in% ineligible_schools$placement) 
                                              & !(school_ids %in% schools_to_swap[1])], 1)
      
      # find acm in schools_to_swap[2] who does not have roommates on schools_to_swap[1] (and who was not manually placed)
      school1_roommates <- candidate_placements_df$Roommate.Names[candidate_placements_df$placement == schools_to_swap[1]]
      school2_frame <- candidate_placements_df[(candidate_placements_df$placement == schools_to_swap[2]
                                                & is.na(candidate_placements_df$Manual.Placement)), ]

      swap2 <- sample(school2_frame$acm_id[is.na(school2_frame$Roommate.Names)
                                           | !(school2_frame$Roommate.Names %in% school1_roommates)], 1)

    }
     
    # Swap the team assignment of those 2 ACMs - NOTE this is done by index, and we use acm_id as index
    candidate_placements_df$placement <- replace(candidate_placements_df$placement, c(swap1, swap2), candidate_placements_df$placement[c(swap2, swap1)])
     
    candidate_score <- calculate_score(candidate_placements_df, school_df)
    trace[i+1, 2:10] <- candidate_score

    if (temp > 0) {
      ratio = exp((placement_score - candidate_score$aggr_score) / temp)
    } else {
      ratio = as.numeric(candidate_score$aggr_score < placement_score)
    }
    
    # Used for bug testing
    # if (is.na(ratio)){
    #   return(list(placement_score=as.data.frame(placement_score),
    #               candidate_score=as.data.frame(candidate_score),
    #               best_placements=best_placements,
    #               trace=trace))
    # }
    
    if (runif(1) < ratio) {
      team_placements_df = candidate_placements_df
      placement_score = candidate_score$aggr_score
      all_scores = candidate_score
    
      if (placement_score < best_score) {
        best_placements = team_placements_df
        best_score = placement_score
        best_score_diff = all_scores
      }
    }
    
  }
  # Add best scores to the last row of trace
  trace[(number_of_iterations+2), 2:10] <- best_score_diff
  
  # Merge in School Name and all survey info
  cols.x <- c("acm_id", "placement")
  cols.y <- c("School", "sch_id")
  best_placements <- merge(best_placements[, cols.x], school_df[, cols.y], by.x = "placement", by.y = "sch_id", all.x = TRUE)
  best_placements <- merge(best_placements, acm_df, by = "acm_id", all.x = TRUE)
  
  # Merge in commute info
  if(consider_commutes == "Yes"){
    best_placements <- within(best_placements, id_dest <- paste(acm_id, School, sep = "_"))
    commutes <- dt_commutes[id_dest %in% best_placements$id_dest, ]
    commutes <- commutes[,c("acm_id", "Commute.Time", "Commute.Rank", "Home.Address")]
    best_placements <- merge(best_placements, commutes, by = "acm_id", all.x = TRUE)
    best_placements$Commute.Time <- best_placements$Commute.Time
  } else {
    best_placements$Commute.Time <- NA
    best_placements$Commute.Rank <- NA
    best_placements$Home.Address <- NA
  }

  # Create one Tutoring Experience Grades Column
  tut_exp_cols = c("Tutoring.Experience.ES",                      
                   "Tutoring.Experience.MS",
                   "Tutoring.Experience.HS")
  best_placements[, tut_exp_cols][best_placements[, tut_exp_cols] == ""] <- NA
  best_placements$Tutoring.Experience.Grades <- apply(best_placements[, tut_exp_cols], 1, function(x) toString(na.omit(x)))
  
  # Create one Grade Level Preference Column
  grd_lvl_pref_cols = c("Grade.Lvl.Pref.ES",
                        "Grade.Lvl.Pref.MS",
                        "Grade.Lvl.Pref.HS")
  best_placements[, grd_lvl_pref_cols][best_placements[, grd_lvl_pref_cols] == ""] <- NA
  best_placements$Grade.Lvl.Pref <- apply(best_placements[, grd_lvl_pref_cols ], 1, function(x) toString(na.omit(x)))
  
  cols <- c("acm_id",
            "Full.Name",
            "Pref.Name",
            "placement",
            "School",
            "Gender",
            "Race.Ethnicity", 
            "Attnd.CY.School",
            "Language.Ability.Spanish",
            "Tutoring.Experience.Months",
            "Tutoring.Experience.Grades",
            "Grade.Lvl.Pref",
            "Teaching.Credential",
            "Tutoring.Preference",
            "Math.Confidence",
            "Birth.Date",
            "Educational.Attainment",
            # "Did you work closely with a City Year member or were you part of the Young Heroes program?",
            # "Do you have a pre-existing relationship with anyone at City Year Chicago (corps or staff)?",
            # "Please list their names:",
            # "You are presented with a project to plan. You would most likely work with your team in which of the following ways?",
            # "When you are under pressure to get an assignment in on time, how do you normally react?",
            # "If people were to describe you in one word, which of the following would it be?",
            # "When given a new project, your first response is which of the following?",
            # "Becoming a City Year corps member often comes with a number of uncertainties. Of the following, which is of biggest concern to you?", 
            "Roommate.Names",
            "Home.Address",
            "Travel.Method",
            "Commute.Time",
            "Commute.Rank",
            "Manual.Placement")
  
  best_placements <- best_placements[, cols]
  
  best_placements <- best_placements[order(best_placements$placement),]
  
  best_placements$acm_id[best_placements$acm_id > nrow(acm_enc)] <- 800:(800 + sum(school_df$size) - nrow(acm_enc) - 1)
  
  return(list(best_placements=best_placements, 
              best_score=best_score,
              diff_scores=best_score_diff,
              trace=trace))
}


# Visualize Error Over Time

# traceplot <- function(trace){
#   library(ggplot2)
# 
#   ggplot(data = trace, aes(x = iter, y = score)) +
#     geom_point() +
#     coord_cartesian(ylim = c(1e3, 1e4))
# }

# Full Application

acm_enc <- encode_acm_df(acm_df)
school_targets <- school_config(school_df, acm_enc)
team_placements_df <- initial_placement(acm_enc, school_targets, prevent_roommates)

output <- run_intermediate_annealing_process(starting_placements = team_placements_df, school_df = school_targets, best_placements = team_placements_df, best_score = 1e12, starting_iteration = 1, number_of_iterations = number_iterations, center_scale=runif(1, 1e-3, 0.25), width_scale=runif(1, 1e-3, 0.25))

best_placements <- output$best_placements

# Hide "blown up" scores for a smoother, more interpretable graph
if(output$best_score < 1000000){
  trace <- output$trace[output$trace$score < 1000000, ]
} else {
  trace <- output$trace
}

#write.table(output$best_placements, file = paste(root_dir, "Output - Team Placements (", gsub(":", ".", Sys.time()), ").csv", sep = ""), sep=",", row.names=FALSE, na = "")
#write.table(output$trace, file = paste(root_dir, "Output - Trace (", gsub(":", ".", Sys.time()), ").csv", sep = ""), sep=",", row.names=FALSE, na = "")

```

```{r Visualizations: Number Teams at Various % Ethnic Representations}
ethnicity_eths <- 
    team_placements_df %>%
    group_by(placement, 
             Race.Ethnicity.African.American.Black, 
             Race.Ethnicity.White.Caucasian, 
             Race.Ethnicity.Asian,
             Race.Ethnicity.Hispanic.Latino,
             Race.Ethnicity.Middle.Eastern,
             Race.Ethnicity.Native.Hawaiian.Pacific.Islander,
             Race.Ethnicity.American.Indian.Alaskan.Native,
             Race.Ethnicity.Other) %>%
    dplyr::summarize(n_eths = n()) %>%
    group_by(placement) %>%
    dplyr::mutate(pct_eths = n_eths/sum(n_eths) * n_eths / sum(n_eths)) %>%
    dplyr::mutate(avg_eths_rep = sum(pct_eths)) %>%
    summarize(avg_eths_rep = mean(avg_eths_rep))

hist(ethnicity_eths$avg_eths_rep, breaks = 7, main = "Number Teams at Various % Ethnic Representations", xlab = "% Ethnic Representation", freq = TRUE, col = "grey", plot = TRUE, labels = FALSE)

hist(best_placements$Commute.Time, breaks = 10, main = "Number ACMs at Various # Minutes Commuting", xlab = "# Minutes Commuting", freq = TRUE, col = "grey", plot = TRUE, labels = FALSE)
trace
```


```{r Check Roommates}
dplyr::select(best_placements, c(placement, Manual.Placement, Roommate.Names)) %>%
  arrange(placement)

roommie_violations <- 
    best_placements %>% 
      filter(!is.na(Roommate.Names)) %>%
      group_by(placement) %>%
      count(Roommate.Names) %>%
      filter(n > 1)

roommie_violations
```