# Generated by Django 2.0.4 on 2018-04-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_survey', models.BooleanField(default=True, verbose_name='Did you use the nation-wide survey?')),
                ('n_iterations', models.IntegerField(default=1000, verbose_name='How many iterations?')),
                ('prevent_roommates', models.BooleanField(default=True, verbose_name='Prevent roommates from serving on the same team?')),
                ('consider_commutes', models.BooleanField(default=False, verbose_name='Consider commute times?')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateTimeField(verbose_name='Date of run')),
            ],
        ),
        migrations.AddField(
            model_name='parameters',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procedure.Run'),
        ),
    ]
