# Generated by Django 2.0.4 on 2018-04-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='ParameterSet',
        ),
    ]
