# Generated by Django 2.0.4 on 2018-04-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_auto_20180418_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunParameters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(verbose_name='Date of run')),
                ('national_survey', models.BooleanField(default=True, verbose_name='Did you use the nation-wide survey?')),
                ('n_iterations', models.IntegerField(default=1000, verbose_name='How many iterations?')),
                ('prevent_roommates', models.BooleanField(default=True, verbose_name='Prevent roommates from serving on the same team?')),
                ('consider_commutes', models.BooleanField(default=False, verbose_name='Consider commute times?')),
            ],
        ),
        migrations.RemoveField(
            model_name='parameterset',
            name='run',
        ),
        migrations.DeleteModel(
            name='ParameterSet',
        ),
        migrations.DeleteModel(
            name='Run',
        ),
    ]
