# Generated by Django 2.0.4 on 2018-04-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
