# Generated by Django 2.0.4 on 2018-04-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0006_auto_20180425_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runparameters',
            old_name='n_iterations',
            new_name='number_iterations',
        ),
        migrations.RenameField(
            model_name='runparameters',
            old_name='national_survey',
            new_name='used_surveygizmo',
        ),
    ]
