# Generated by Django 2.0.4 on 2018-04-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0007_auto_20180428_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runparameters',
            name='consider_commutes',
        ),
        migrations.AddField(
            model_name='runparameters',
            name='api_key',
            field=models.CharField(default='', max_length=100, verbose_name='Google API Key (required to calculate commutes)'),
        ),
        migrations.AddField(
            model_name='runparameters',
            name='calculate_commutes',
            field=models.BooleanField(default=False, verbose_name='Calcute commute times? If you already calculated commutes in a previous run, re-calculating is not required.'),
        ),
        migrations.AlterField(
            model_name='runparameters',
            name='number_iterations',
            field=models.IntegerField(default=100, verbose_name='How many iterations?'),
        ),
        migrations.AlterField(
            model_name='runparameters',
            name='used_surveygizmo',
            field=models.BooleanField(default=False, verbose_name='Did you use the nation-wide survey?'),
        ),
    ]
