# Generated by Django 2.0.4 on 2018-05-02 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0009_auto_20180428_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='runparameters',
            name='commute_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Set a travel date for commute calculations. Choose a date that should represent normal traffic.'),
        ),
    ]
